[theme]
primaryColor = "#00C853"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
